namespace Backend2023.Hubs;

/// <summary>
///     Answer object sent after a complete voice message has been submitted.
/// </summary>
/// <param name="UnderstoodText">Speech2Text result of the submitted voice message.</param>
/// <param name="AnswerText">Generated answer text.</param>
/// <param name="Base64EncodedMp3">MP3 response generated by Text2Speech.</param>
public record AudioResponse(string UnderstoodText, string AnswerText, string Base64EncodedMp3);
